 set_property IOSTANDARD LVCMOS33 [get_ports {ao[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ai[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ai[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports vo]
set_property IOSTANDARD LVCMOS33 [get_ports s_vi]
set_property IOSTANDARD LVCMOS33 [get_ports {di[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ai[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ao[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ai[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ao[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {di[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ao[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports takein]
set_property IOSTANDARD LVCMOS33 [get_ports {do[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do[3]}]
set_property PACKAGE_PIN V10 [get_ports s_vi]
set_property PACKAGE_PIN U11 [get_ports {ai[3]}]
set_property PACKAGE_PIN U12 [get_ports {ai[2]}]
set_property PACKAGE_PIN H6 [get_ports {ai[1]}]
set_property PACKAGE_PIN T13 [get_ports {ai[0]}]
set_property PACKAGE_PIN R16 [get_ports {di[4]}]
set_property PACKAGE_PIN U8 [get_ports {di[3]}]
set_property PACKAGE_PIN T8 [get_ports {di[2]}]
set_property PACKAGE_PIN R13 [get_ports {di[1]}]
set_property PACKAGE_PIN U18 [get_ports {di[0]}]
set_property PACKAGE_PIN H17 [get_ports {ao[0]}]
set_property PACKAGE_PIN K15 [get_ports {ao[1]}]
set_property PACKAGE_PIN J13 [get_ports {ao[2]}]
set_property PACKAGE_PIN N14 [get_ports {ao[3]}]

set_property PACKAGE_PIN T18 [get_ports takein]
set_property PACKAGE_PIN V11 [get_ports vo]

set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 1000000000.000 -name sys_clk_pin -waveform {0.000 500000000.000} -add [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {do_min[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_min[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_min[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_min[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_min[0]}]
set_property PACKAGE_PIN V14 [get_ports {do_min[4]}]
set_property PACKAGE_PIN V15 [get_ports {do_min[3]}]
set_property PACKAGE_PIN T16 [get_ports {do_min[2]}]
set_property PACKAGE_PIN U14 [get_ports {do_min[1]}]
set_property PACKAGE_PIN T15 [get_ports {do_min[0]}]
set_property PACKAGE_PIN R18 [get_ports {do[0]}]
set_property PACKAGE_PIN V17 [get_ports {do[1]}]
set_property PACKAGE_PIN U17 [get_ports {do[2]}]
set_property PACKAGE_PIN U16 [get_ports {do[3]}]
set_property PACKAGE_PIN V16 [get_ports {do[4]}]
